### PR TITLE
[TASK] Add typo3/tailor handling for docs rendering

### PR DESCRIPTION
**Pull request by DanielSiepmann**
Extend existing test to also test special handling for known packages.

### CODE REVIEW

**Comment by DanielSiepmann** [comment]
This is only a single place, there are more places to adjust

**Comment by DanielSiepmann** [comment]
I'll try to extend the PR and refactor parts to reduce amount of code to adjust.

But that might take some time.

**Comment by DanielSiepmann** [comment]
I tried to refactor. But I guess current code is actually okay.
I didn't find a way to refactor to a better result. It always ended up in a bigger mess.

Please check if I missed anything as I don't have a running version of intercept, just the unit tests.

**Comment by DanielSiepmann** [comment]
Not sure how to handle GitHub Actions. Looks like it needs some variables which are missing in my fork, so CI can't be executed. https://github.com/DanielSiepmann/site-intercept/runs/2896153111
Maybe you can ignore my fork and push a new branch with changes within this repo?

**Review by susannemoog — APPROVED** [review]

**Pull request merged**
