### PR TITLE
[TASK] Add shortcut to `typo3/tailor` documentation

### PR DESCRIPTION
**Pull request by alexander-nitsche**

### CODE REVIEW

**Comment by susannemoog** [comment]
@alexander-nitsche I still haven't quite got why this is necessary. As far as I know, surf is basically a legacy fix - do we need to introduce the same for new docs? I did not quite manage to follow the discussion about this.

**Comment by alexander-nitsche** [comment]
@susannemoog : Following the discussion it is not only a legacy fix but also the current way to provide a link to the _latest_ version of a document. See for example https://github.com/TYPO3/Surf#documentation which actively links to https://docs.typo3.org/surf/.

**Review by susannemoog — APPROVED** [review]

**Review by susannemoog — CHANGES_REQUESTED** [review]
But the target is invalid (there is currently no rendered 1.0) and I don't get, why we can't link to https://docs.typo3.org/other/typo3/tailor/master/en-us/ which is in this case latest?

**Comment by alexander-nitsche** [comment]
I think we are running in circles :) Let's discuss this in Slack again and write down here only the result.

**Comment by alexander-nitsche** [comment]
As discussed in Slack: Avoid introducing shortcuts in intercept's nginx configuration which might redirect to outdated documentation versions. Use the documentation url of the latest development version instead:

* https://docs.typo3.org/other/typo3/surf/master/en-us/

See https://github.com/TYPO3-Documentation/T3DocTeam/issues/160 for further details.

Closing this PR.

**Pull request closed without merging**
